# Header
menu:
  Docs: /docs/index.html#doc--dojo__cli__master
  Tutorials: /tutorials/000_local_installation/
  Blog: /blog
  Github: https://github.com/dojo/meta
  Gitter: https://gitter.im/dojo/dojo
  Twitter: https://twitter.com/dojo
rss: /atom.xml


# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-3242977-15
favicon: /images/favicons/favicon.ico
twitter: https://twitter.com/dojo
github: https://github.com/dojo/meta
